#!/usr/bin/env python3
"""NebulaOS build attestation v2 - HMAC-SHA256 over a canonical field set.

WHAT THIS IS FOR

A v1 attestation (.nebulaos-build-verified, written by run-nebulaos-build.sh)
is an UNAUTHENTICATED assertion. It is a plain text file in a world-writable
/var/tmp tree, so anything that can write the file can claim any build passed.
That was adequate while the only consumer was a human reading it, and is not
adequate now that a Hardware Agent decides whether to flash a printer on the
strength of it.

v2 adds one property and only one: the reader can tell whether the fields were
produced by a holder of the attestation key. It is a MAC, not a signature -
there is one key, held by the human who runs this project, and both signing and
verification need it. That is the right shape here: the verifier and the signer
are the same person's machine, and a public-key scheme would add key
distribution for no gain.

WHAT IT DELIBERATELY DOES NOT DO

It does not upgrade v1 files. A v1 attestation that happens to sit next to a v2
one stays v1 and stays unauthenticated - `verify` refuses anything whose
ATTESTATION_VERSION is not exactly 2. Silently treating an old unauthenticated
record as authenticated would defeat the entire point of adding the MAC.

It does not decide policy. It answers "were these exact bytes MACed by this
key" and nothing else. Whether a given BUILD_PROFILE is good enough to flash a
printer is the caller's decision, made on fields this tool has proven authentic.

THE KEY

  ~/.config/nebulaos-attest/attest.key     (override: NEBULAOS_ATTEST_KEY)

Human-created, never generated by an agent. Enforced on every use:

  - the path must be a REGULAR FILE, checked with lstat, so a symlink is
    refused rather than followed. A symlink would let anything that can create
    one in that directory redirect reads to a file it controls.
  - mode 0600 exactly, and the containing directory 0700 exactly. Not "at most"
    - an exact match, because a key that is group-readable is not a key.
  - owned by the invoking user.
  - non-empty, and at least 32 bytes of material.

The key content is NEVER placed in argv, never passed through the environment,
and never printed. Only KEY_ID - a one-way tag derived from it - appears in
output, so two attestations can be told apart without revealing anything.

CANONICALISATION

The MAC covers a canonical serialisation, not the file's literal bytes, so
reordering or reformatting fields cannot change what was authenticated:

  - every field except MAC
  - each as KEY=VALUE, KEY uppercase [A-Z0-9_]
  - sorted by KEY, joined with \n, one trailing \n
  - prefixed by a domain-separation string that names the version

Domain separation matters: without it a MAC computed over some other NebulaOS
structure with the same key could be replayed as an attestation.

Values may not contain newlines or NUL - both would make the line format
ambiguous - and duplicate keys are refused rather than last-one-wins, since
"which one did the MAC cover" has no good answer.

USAGE

  nebulaos-attest.py sign   [--in FILE] [--out FILE]
  nebulaos-attest.py verify [--in FILE] [--require KEY=VALUE]...
  nebulaos-attest.py keyid

`sign` reads KEY=VALUE lines (stdin by default), validates the required v2
field set, appends MAC=, and writes the result. `verify` reads a signed
attestation, recomputes the MAC in constant time, and additionally enforces any
--require KEY=VALUE constraints, so a caller can say "and it must be a release
profile" in the same breath as "and it was really signed".

Exit codes: 0 ok, 2 refused (bad input, bad key, policy), 3 verification
failed. A failed verification is deliberately a DIFFERENT code from a refusal,
so a caller cannot conflate "could not check" with "checked and it was forged".
"""

import argparse
import hashlib
import hmac
import os
import stat
import sys

ATTESTATION_VERSION = "2"

# Bumping the version string here changes every MAC, which is the intent: a v2
# attestation must not verify under a future v3 scheme or vice versa.
_DOMAIN = b"NebulaOS-build-attestation-v2\x00"

DEFAULT_KEY_PATH = os.path.join(
    os.path.expanduser("~"), ".config", "nebulaos-attest", "attest.key"
)

# Every field a v2 attestation must carry. These are exactly the facts a
# Hardware Agent needs in order to decide whether an artifact set may be
# installed, and the ones a later investigation needs in order to reconstruct
# which build produced it. A missing one is a refusal, never a blank: an
# attestation that is present but hollow reads as evidence while proving
# nothing, which is worse than no attestation at all.
REQUIRED_FIELDS = (
    "ATTESTATION_VERSION",
    "KEY_ID",
    "SOURCE_HEAD",
    "SOURCE_REPO",
    "SOURCE_PUBLISHED_TIP",
    "BUILD_LAUNCHER_BLOB",
    "BUILD_MODE",
    "BUILD_PROFILE",
    "CCACHE",
    "BUILD_LOG_SHA256",
    "XIMAGE_SHA256",
    "XIMAGE_SIZE",
    "ROOTFS_SQUASHFS_SHA256",
    "ROOTFS_SQUASHFS_SIZE",
    "MANIFEST_SHA256",
    "BUILDER_DIGEST",
    "SOURCE_DATE_EPOCH",
    "BUILD_RUN",
    "ATTESTED_AT",
)

_SHA256_FIELDS = (
    "BUILD_LOG_SHA256",
    "XIMAGE_SHA256",
    "ROOTFS_SQUASHFS_SHA256",
    "MANIFEST_SHA256",
)


class Refused(Exception):
    """Input, key or policy problem. Never means 'the MAC was wrong'."""


class VerifyFailed(Exception):
    """The MAC did not match, or a --require constraint was not met."""


# --------------------------------------------------------------------------
# key handling
# --------------------------------------------------------------------------

def key_path():
    return os.environ.get("NEBULAOS_ATTEST_KEY") or DEFAULT_KEY_PATH


def load_key():
    """Read the attestation key, refusing anything about it that is not exact.

    Uses lstat deliberately: os.path.isfile() follows symlinks, so a symlink
    planted in the key directory would pass it and then be read. Here a symlink
    is simply not a regular file and is refused.
    """
    path = key_path()

    try:
        st = os.lstat(path)
    except FileNotFoundError:
        raise Refused(
            "no attestation key at %s.\n"
            "       This key is created by a human, never by an agent and never by this tool.\n"
            "       Create it out of band, for example:\n"
            "         mkdir -p -m 0700 %s\n"
            "         head -c 64 /dev/urandom > %s\n"
            "         chmod 0600 %s"
            % (path, os.path.dirname(path), path, path)
        )
    except OSError as exc:
        raise Refused("cannot stat the attestation key %s: %s" % (path, exc))

    if stat.S_ISLNK(st.st_mode):
        raise Refused(
            "the attestation key path %s is a symlink.\n"
            "       Refusing to follow it: a symlink in the key directory lets whoever can\n"
            "       create it choose which bytes get used as the key." % path
        )
    if not stat.S_ISREG(st.st_mode):
        raise Refused("the attestation key %s is not a regular file" % path)

    if st.st_uid != os.geteuid():
        raise Refused(
            "the attestation key %s is owned by uid %d, not by the invoking user (uid %d)"
            % (path, st.st_uid, os.geteuid())
        )

    mode = stat.S_IMODE(st.st_mode)
    if mode != 0o600:
        raise Refused(
            "the attestation key %s has mode %04o, expected exactly 0600.\n"
            "       Fix with: chmod 0600 %s" % (path, mode, path)
        )

    parent = os.path.dirname(path) or "."
    try:
        pst = os.stat(parent)
    except OSError as exc:
        raise Refused("cannot stat the key directory %s: %s" % (parent, exc))
    pmode = stat.S_IMODE(pst.st_mode)
    if pmode != 0o700:
        raise Refused(
            "the key directory %s has mode %04o, expected exactly 0700.\n"
            "       Fix with: chmod 0700 %s" % (parent, pmode, parent)
        )

    with open(path, "rb") as fh:
        material = fh.read()

    if len(material) < 32:
        raise Refused(
            "the attestation key %s holds %d byte(s); at least 32 are required"
            % (path, len(material))
        )

    return material


def key_id(material):
    """A one-way tag for a key, safe to publish in an attestation.

    Separately domain-separated from the MAC itself so that KEY_ID can never be
    a MAC over attacker-chosen data.
    """
    return hashlib.sha256(b"NebulaOS-attest-key-id\x00" + material).hexdigest()[:16]


# --------------------------------------------------------------------------
# field parsing / canonicalisation
# --------------------------------------------------------------------------

def parse_fields(text):
    """Parse KEY=VALUE lines into an ordered dict, refusing ambiguity.

    Blank lines and # comments are ignored so a caller can build the input with
    a heredoc and keep it readable. Everything else must be a well-formed
    assignment.
    """
    fields = {}
    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise Refused("line %d is not KEY=VALUE: %r" % (lineno, raw))
        name, _, value = line.partition("=")
        name = name.strip()
        if not name:
            raise Refused("line %d has an empty field name" % lineno)
        for ch in name:
            if not (ch.isdigit() or ch == "_" or (ch.isalpha() and ch.isupper() and ch.isascii())):
                raise Refused(
                    "line %d: field name %r must be uppercase ASCII letters, digits and underscore"
                    % (lineno, name)
                )
        if name in fields:
            raise Refused(
                "field %s appears more than once. Refusing rather than picking one:\n"
                "       there is no defensible answer to which copy the MAC covered." % name
            )
        if "\x00" in value:
            raise Refused("field %s contains a NUL byte" % name)
        fields[name] = value
    return fields


def canonical_bytes(fields):
    """The exact bytes the MAC is computed over.

    Sorted, so field order in the file is irrelevant; domain-separated, so a
    MAC over some other structure cannot be replayed here.
    """
    parts = []
    for name in sorted(fields):
        if name == "MAC":
            continue
        parts.append("%s=%s" % (name, fields[name]))
    return _DOMAIN + ("\n".join(parts) + "\n").encode("utf-8")


def compute_mac(material, fields):
    return hmac.new(material, canonical_bytes(fields), hashlib.sha256).hexdigest()


def validate_v2(fields):
    """Structural validation of a v2 field set, independent of the MAC.

    Runs before signing so a malformed attestation is never produced, and after
    a successful verify so a MACed-but-nonsensical record is still refused.
    """
    version = fields.get("ATTESTATION_VERSION")
    if version != ATTESTATION_VERSION:
        raise Refused(
            "ATTESTATION_VERSION is %r, expected %r.\n"
            "       v1 attestations are NOT upgraded here. A v1 record is unauthenticated and\n"
            "       stays that way; re-attest the build under v2 instead."
            % (version, ATTESTATION_VERSION)
        )

    missing = [f for f in REQUIRED_FIELDS if f not in fields]
    if missing:
        raise Refused("missing required v2 field(s): %s" % ", ".join(missing))

    empty = [f for f in REQUIRED_FIELDS if not fields[f].strip()]
    if empty:
        raise Refused(
            "required v2 field(s) present but empty: %s.\n"
            "       A hollow attestation reads as evidence while proving nothing." % ", ".join(empty)
        )

    for name in _SHA256_FIELDS:
        value = fields[name]
        if len(value) != 64 or any(c not in "0123456789abcdef" for c in value):
            raise Refused("%s is not a 64-character lowercase hex SHA-256: %r" % (name, value))

    head = fields["SOURCE_HEAD"]
    if len(head) != 40 or any(c not in "0123456789abcdef" for c in head):
        raise Refused("SOURCE_HEAD is not a full 40-character lowercase hex SHA: %r" % head)

    for name in ("XIMAGE_SIZE", "ROOTFS_SQUASHFS_SIZE", "SOURCE_DATE_EPOCH"):
        value = fields[name]
        if not value.isdigit():
            raise Refused("%s must be a decimal integer: %r" % (name, value))

    # The one policy fact baked in here rather than left to callers: a release
    # profile with ccache enabled is a contradiction in terms, and the whole
    # release/dev split exists to keep a compiler cache out of qualification.
    # Refusing at signing time means such an attestation cannot exist to be
    # argued about later.
    if fields["BUILD_PROFILE"] == "release" and fields["CCACHE"] != "disabled":
        raise Refused(
            "BUILD_PROFILE=release with CCACHE=%r.\n"
            "       A release build must have ccache disabled; refusing to attest otherwise."
            % fields["CCACHE"]
        )


# --------------------------------------------------------------------------
# serialisation
# --------------------------------------------------------------------------

def render(fields):
    """Human-readable output: required fields first in declared order, then any
    extras alphabetically, then MAC last. The MAC covers the canonical form, so
    this ordering is presentation only and can change without breaking anything.
    """
    lines = []
    for name in REQUIRED_FIELDS:
        if name in fields:
            lines.append("%s=%s" % (name, fields[name]))
    for name in sorted(fields):
        if name not in REQUIRED_FIELDS and name != "MAC":
            lines.append("%s=%s" % (name, fields[name]))
    if "MAC" in fields:
        lines.append("MAC=%s" % fields["MAC"])
    return "\n".join(lines) + "\n"


def read_input(path):
    if path in (None, "-"):
        return sys.stdin.read()
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return fh.read()
    except OSError as exc:
        raise Refused("cannot read %s: %s" % (path, exc))


# --------------------------------------------------------------------------
# subcommands
# --------------------------------------------------------------------------

def cmd_sign(args):
    material = load_key()
    fields = parse_fields(read_input(args.infile))

    if "MAC" in fields:
        raise Refused(
            "the input already carries a MAC. Refusing to re-sign:\n"
            "       re-signing an existing attestation is how a forged one gets laundered\n"
            "       into a valid one. Build the field set from the real facts instead."
        )

    # KEY_ID is derived, never accepted from the caller: letting the input claim
    # a KEY_ID would let a forged record name a key it was not signed with.
    kid = key_id(material)
    if fields.get("KEY_ID") not in (None, "", kid):
        raise Refused(
            "the input states KEY_ID=%s but the key in use is %s"
            % (fields["KEY_ID"], kid)
        )
    fields["KEY_ID"] = kid

    # ATTESTATION_VERSION is NOT defaulted. An earlier revision did
    # setdefault(...ATTESTATION_VERSION), which meant a v1 field set quietly
    # acquired "2" and was then refused for the unrelated reason that it was
    # missing v2 fields. The refusal was correct but the reason was wrong, and a
    # refusal for the wrong reason is one that stops being correct as soon as the
    # field list changes. Requiring the caller to state the version explicitly
    # makes "this is not a v2 record" the actual, stable reason.
    if "ATTESTATION_VERSION" not in fields:
        raise Refused(
            "the input does not state ATTESTATION_VERSION.\n"
            "       This tool signs v2 attestations only, and will not infer the version:\n"
            "       a v1 field set must be rebuilt as v2 from the real facts, never relabelled."
        )

    validate_v2(fields)
    fields["MAC"] = compute_mac(material, fields)

    out = render(fields)
    if args.outfile in (None, "-"):
        sys.stdout.write(out)
    else:
        # 0600 and atomic: an attestation that is briefly world-readable or
        # briefly truncated is an attestation someone can race.
        tmp = args.outfile + ".tmp.%d" % os.getpid()
        fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(out)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp, args.outfile)
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
        sys.stderr.write("ATTESTATION_WRITTEN=%s\n" % args.outfile)
    return 0


def cmd_verify(args):
    material = load_key()
    fields = parse_fields(read_input(args.infile))

    claimed = fields.get("MAC")
    if not claimed:
        raise VerifyFailed("the attestation carries no MAC")

    expected = compute_mac(material, fields)

    # Constant time. A byte-by-byte compare leaks, through timing, how much of a
    # guessed MAC was right, which is exactly the oracle a forger wants.
    if not hmac.compare_digest(claimed, expected):
        raise VerifyFailed(
            "MAC mismatch - these fields were not attested by this key.\n"
            "       Either the attestation was altered after signing, or it was produced\n"
            "       with a different key."
        )

    kid = key_id(material)
    if fields.get("KEY_ID") != kid:
        # Unreachable through a MAC forgery (KEY_ID is covered by the MAC), but
        # checked anyway so the failure is named precisely if it ever happens.
        raise VerifyFailed(
            "KEY_ID in the attestation (%s) is not this key (%s)" % (fields.get("KEY_ID"), kid)
        )

    validate_v2(fields)

    for constraint in args.require or []:
        if "=" not in constraint:
            raise Refused("--require expects KEY=VALUE, got %r" % constraint)
        name, _, want = constraint.partition("=")
        got = fields.get(name)
        if got != want:
            raise VerifyFailed(
                "required %s=%s but the attestation says %s=%s"
                % (name, want, name, "<absent>" if got is None else got)
            )

    print("ATTESTATION_VALID=YES")
    print("ATTESTATION_VERSION=%s" % fields["ATTESTATION_VERSION"])
    print("KEY_ID=%s" % kid)
    print("SOURCE_HEAD=%s" % fields["SOURCE_HEAD"])
    print("BUILD_PROFILE=%s" % fields["BUILD_PROFILE"])
    print("BUILD_MODE=%s" % fields["BUILD_MODE"])
    print("XIMAGE_SHA256=%s" % fields["XIMAGE_SHA256"])
    print("ROOTFS_SQUASHFS_SHA256=%s" % fields["ROOTFS_SQUASHFS_SHA256"])
    return 0


def cmd_keyid(args):
    print("KEY_ID=%s" % key_id(load_key()))
    print("KEY_PATH=%s" % key_path())
    return 0


def main(argv):
    parser = argparse.ArgumentParser(
        prog="nebulaos-attest.py",
        description="NebulaOS build attestation v2 (HMAC-SHA256)",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_sign = sub.add_parser("sign", help="MAC a v2 field set read as KEY=VALUE lines")
    p_sign.add_argument("--in", dest="infile", default="-")
    p_sign.add_argument("--out", dest="outfile", default="-")
    p_sign.set_defaults(func=cmd_sign)

    p_verify = sub.add_parser("verify", help="verify a signed v2 attestation")
    p_verify.add_argument("--in", dest="infile", default="-")
    p_verify.add_argument(
        "--require",
        action="append",
        metavar="KEY=VALUE",
        help="additionally require this exact field value (repeatable)",
    )
    p_verify.set_defaults(func=cmd_verify)

    p_keyid = sub.add_parser("keyid", help="print the KEY_ID of the configured key")
    p_keyid.set_defaults(func=cmd_keyid)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except Refused as exc:
        sys.stderr.write("NEBULAOS_ATTEST=REFUSED\nREASON: %s\n" % exc)
        return 2
    except VerifyFailed as exc:
        sys.stderr.write("ATTESTATION_VALID=NO\nREASON: %s\n" % exc)
        return 3


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
